services:
  container-ctl:
    build:
      context: .
      dockerfile: Dockerfile
    image: gsbelarus/container-ctl:latest
    container_name: container-ctl
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      CONTAINER_CTL_DOCKER_SOCKET: /var/run/docker.sock
      CONTAINER_CTL_LISTEN_HOST: ${CONTAINER_CTL_LISTEN_HOST:-0.0.0.0}
      CONTAINER_CTL_LISTEN_PORT: ${CONTAINER_CTL_LISTEN_PORT:-3080}
      CONTAINER_CTL_ALLOW_DELETE: ${CONTAINER_CTL_ALLOW_DELETE:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
    name: proxy_network
